(() => {
'use strict';
const $=id=>document.getElementById(id), auth=HotelVistaAuth.createClient(fetch.bind(window));
let page=0, bookingPage=0,city='',propertyId=null,saveAction=null,busy=false;
const status=message=>{$('admin-status').textContent=message;};
async function api(path,method='GET',data) {
 const headers={Accept:'application/json'};
 if(method!=='GET'){const csrf=await auth.csrf();headers[csrf.headerName]=csrf.token;headers['Content-Type']='application/json';}
 const response=await fetch('/api/admin/'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data),credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000)});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(response.status===403?'Administrator permission required.':response.status===401?'Please sign in again.':body.detail||'Could not save. Check the fields and retry.');
 return body;
}
function button(text,action){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>run(action);return b;}
async function run(action){if(busy)return;busy=true;try{await action();}catch(e){status(e.message);}finally{busy=false;}}
function card(title,details,actions){const el=document.createElement('article');el.className='admin-card';const body=document.createElement('div'),h=document.createElement('h3');h.textContent=title;body.append(h);details.forEach(t=>{const p=document.createElement('p');p.textContent=t;body.append(p);});el.append(body,...actions);return el;}
function field(name,label,value='',type='text',options){const l=document.createElement('label');l.textContent=label;const input=document.createElement(options?'select':type==='textarea'?'textarea':'input');input.name=name;if(options){options.forEach(t=>{const o=document.createElement('option');o.value=t;o.textContent=t;input.append(o);});}else if(type!=='textarea')input.type=type;input.value=value;input.required=true;if(type==='number'){input.min='0';input.step=name==='price'?'.01':'1';}l.append(input);$('editor-fields').append(l);}
function edit(title,fields,save){$('editor-title').textContent=title;$('editor-fields').replaceChildren();$('editor-error').textContent='';fields();saveAction=save;$('editor').showModal();}
$('close-editor').onclick=()=>$('editor').close();
$('editor-form').onsubmit=async e=>{e.preventDefault();$('save-editor').disabled=true;try{await saveAction(Object.fromEntries(new FormData(e.target)));$('editor').close();status('Saved successfully.');}catch(error){$('editor-error').textContent=error.message;}finally{$('save-editor').disabled=false;}};
async function load(){const rows=await api('properties?city='+encodeURIComponent(city)+'&page='+page);$('properties-list').replaceChildren(...rows.slice(0,20).map(p=>card(p.name,[p.city+' · '+p.property_type,p.active?'Active':'Inactive'],[button('Edit',()=>editProperty(p)),button('Manage rooms',()=>loadRooms(p.id,p.name))])));$('previous').disabled=page===0;$('next').disabled=rows.length<=20;$('page-label').textContent='Page '+(page+1);status(rows.length?'Properties loaded.':'No properties found.');}
function editProperty(p={}){edit(p.id?'Edit property':'Add property',()=>{field('name','Name',p.name);field('propertyType','Property type',p.property_type||'HOTEL','text',['HOTEL','RESORT','APARTMENT','HOMESTAY','VILLA','FARMHOUSE','BUNGALOW']);field('city','City',p.city);field('address','Address',p.address);field('description','Description',p.description,'textarea');field('active','Status',String(p.active??true),'text',['true','false']);},async d=>{d.active=d.active==='true';await api('properties'+(p.id?'/'+p.id:''),p.id?'PUT':'POST',d);await load();});}
async function loadRooms(id,name){propertyId=id;$('room-heading').textContent=name||'Room types';$('room-panel').hidden=false;const rows=await api('properties/'+id+'/rooms');$('rooms-list').replaceChildren(...rows.map(r=>card(r.name,[r.capacity+' guests · '+r.total_quantity+' rooms · ₹'+r.base_nightly_price+' / night',r.active?'Active':'Inactive'],[button('Edit room',()=>editRoom(r)),button('Nightly inventory',()=>editInventory(r))])));}
function editRoom(r={}){const parent=propertyId;edit(r.id?'Edit room':'Add room type',()=>{field('name','Name',r.name);field('capacity','Guests per room',r.capacity||2,'number');field('totalQuantity','Total rooms',r.total_quantity||1,'number');field('price','Nightly price (INR)',r.base_nightly_price||0,'number');field('active','Status',String(r.active??true),'text',['true','false']);},async d=>{d.active=d.active==='true';for(const k of ['capacity','totalQuantity','price'])d[k]=Number(d[k]);await api('properties/'+parent+'/rooms'+(r.id?'/'+r.id:''),r.id?'PUT':'POST',d);await loadRooms(parent);});}
function editInventory(r){edit('Inventory · '+r.name,()=>{field('start','First night','','date');field('end','End date (excluded)','','date');field('quantity','Sellable rooms per night',r.total_quantity,'number');$('editor-fields').append(button('View existing nights',async()=>{const f=new FormData($('editor-form'));const rows=await api('rooms/'+r.id+'/inventory?start='+f.get('start')+'&end='+f.get('end'));$('editor-error').textContent=rows.length?rows.map(n=>n.stay_date+': '+n.sellable_quantity+' sellable, '+n.reserved_quantity+' reserved').join('\n'):'No inventory for these dates.';}));},async d=>{d.quantity=Number(d.quantity);await api('rooms/'+r.id+'/inventory','PUT',d);});}
async function loadBookings(){const rows=await api('bookings?page='+bookingPage);$('admin-bookings').replaceChildren(...rows.slice(0,20).map(b=>card(b.property_name,[b.guest_name+' · '+b.reference,b.checkin+' → '+b.checkout,b.status+' · ₹'+b.total_amount],b.status==='CONFIRMED'?[button('Review cancellation',()=>edit('Approve cancellation',()=>{field('reason','Reason for cancelling this booking','','textarea');},async d=>{await api('bookings/'+b.id+'/cancel','POST',d);await loadBookings();}))]:[])));$('bookings-previous').disabled=bookingPage===0;$('bookings-next').disabled=rows.length<=20;status(rows.length?'Bookings loaded.':'No bookings yet.');}
$('city-filter').onsubmit=e=>{e.preventDefault();city=new FormData(e.target).get('city');page=0;run(load);};
$('add-property').onclick=()=>editProperty();$('add-room').onclick=()=>editRoom();
$('previous').onclick=()=>run(async()=>{page=Math.max(0,page-1);await load();});$('next').onclick=()=>run(async()=>{page++;await load();});
$('bookings-previous').onclick=()=>run(async()=>{bookingPage=Math.max(0,bookingPage-1);await loadBookings();});$('bookings-next').onclick=()=>run(async()=>{bookingPage++;await loadBookings();});
$('properties-tab').onclick=()=>{$('properties-view').hidden=false;$('bookings-view').hidden=true;};$('bookings-tab').onclick=()=>run(async()=>{$('properties-view').hidden=true;$('bookings-view').hidden=false;await loadBookings();});
window.addEventListener('hotelvista-session',e=>{if(!e.detail||e.detail.role!=='ADMIN'){$('admin-workspace').hidden=true;$('editor').close();status('Sign in with an administrator account to manage properties.');}});
run(async()=>{const account=await auth.me();if(account?.role!=='ADMIN'){status('Sign in with an administrator account to manage properties.');return;}$('admin-workspace').hidden=false;await load();});
})();
