/* Demo catalogue only. Replace this adapter with the future Spring API. */
window.HOTEL_VISTA = {
  destinations: [
    {city:"New Delhi",query:"Delhi",image:"assets/optimized/destinations-delhi.webp",caption:"History meets the everyday"},
    {city:"Goa",query:"Goa",image:"assets/optimized/destinations-goa.webp",caption:"Take the coastal route"},
    {city:"Jaipur",query:"Jaipur",image:"assets/optimized/destinations-jaipur.webp",caption:"A little royal treatment"},
    {city:"Mumbai",query:"Mumbai",image:"assets/optimized/destinations-mumbai.webp",caption:"The city, at your pace"},
    {city:"Bengaluru",query:"Bengaluru",image:"assets/optimized/destinations-bangalore.webp",caption:"Gardens and good coffee"},
    {city:"Udaipur",query:"Udaipur",image:"assets/optimized/destinations-udaipur.webp",caption:"Wake up by the water"}
  ],
  properties: [
    {id:"delhi-garden",name:"The Garden House",city:"New Delhi",area:"South Delhi",type:"Hotel",price:4500,capacity:2,rooms:4,image:"assets/optimized/images-delhi-delhi-1.webp",tag:"City escape",amenities:["Wi-Fi","Breakfast","Parking"],description:"A quiet base for a city full of stories.",details:"Settle into a bright king room with a reading corner and space to unwind after a day exploring the capital."},
    {id:"goa-palms",name:"Palm & Tide Retreat",city:"Goa",area:"North Goa",type:"Resort",price:6800,capacity:3,rooms:6,image:"assets/optimized/property-types-resorts.webp",tag:"Slow weekends",amenities:["Wi-Fi","Pool","Breakfast"],description:"Easy afternoons, a pool, and coastal air.",details:"An airy retreat with a private balcony, a shared pool and room for a leisurely breakfast. A relaxed starting point for exploring Goa."},
    {id:"jaipur-courtyard",name:"The Pink Courtyard",city:"Jaipur",area:"Old City",type:"Hotel",price:5200,capacity:2,rooms:5,image:"assets/optimized/images-jaipur-jaipur-1.webp",tag:"Character stays",amenities:["Wi-Fi","Breakfast","Parking"],description:"Warm interiors with a touch of Rajasthan.",details:"A courtyard-inspired city stay with locally inspired interiors, a king bed and a comfortable lounge space."},
    {id:"mumbai-harbour",name:"Harbour House",city:"Mumbai",area:"South Mumbai",type:"Hotel",price:7900,capacity:2,rooms:8,image:"assets/optimized/images-mumbai-mumbai-1.webp",tag:"Urban favourite",amenities:["Wi-Fi","Breakfast"],description:"Your comfortable corner of the big city.",details:"A considered city base with a work desk, a generous bed and an easy place to recharge between outings."},
    {id:"bengaluru-studio",name:"Greenway Studios",city:"Bengaluru",area:"Indiranagar",type:"Apartment",price:3200,capacity:2,rooms:3,image:"assets/optimized/images-bengaluru-bengaluru-1.webp",tag:"Make yourself at home",amenities:["Wi-Fi","Parking"],description:"A little extra space to make your own.",details:"A self-contained studio with a kitchenette, workspace and sitting area. Designed for both a short visit and a longer city break."},
    {id:"udaipur-lake",name:"Lakeview Hideaway",city:"Udaipur",area:"Lakeside",type:"Homestay",price:3800,capacity:3,rooms:2,image:"assets/optimized/property-types-homestays.webp",tag:"A slower pace",amenities:["Wi-Fi","Breakfast"],description:"Unhurried mornings and a lakeside mood.",details:"A cosy homestay-inspired setting with warm common spaces and a comfortable room for a small family."},
    {id:"delhi-studio",name:"Capital Studio Suites",city:"New Delhi",area:"Aerocity",type:"Apartment",price:3500,capacity:3,rooms:5,image:"assets/optimized/images-delhi-delhi-2.webp",tag:"Room to settle in",amenities:["Wi-Fi","Parking"],description:"An easy city base with space to spread out.",details:"An apartment-style suite with a kitchenette, a double bed and an additional guest bed."},
    {id:"chennai-coast",name:"Coral Coast House",city:"Chennai",area:"East Coast Road",type:"Resort",price:6100,capacity:4,rooms:4,image:"assets/optimized/images-chennai-chennai-1.webp",tag:"Family time",amenities:["Wi-Fi","Pool","Parking"],description:"Space for the family, time for the pool.",details:"A family room with two double beds and access to a shared swimming pool. A starting point for a coastal weekend."},
    {id:"hyderabad-grove",name:"The Grove Hyderabad",city:"Hyderabad",area:"Banjara Hills",type:"Hotel",price:4200,capacity:2,rooms:7,image:"assets/optimized/images-hyderabad-hyderabad-1.webp",tag:"City comfort",amenities:["Wi-Fi","Breakfast","Parking"],description:"Comfortable nights after busy city days.",details:"A contemporary double room with a work area and relaxed communal spaces."},
    {id:"jaipur-home",name:"Marigold Homestay",city:"Jaipur",area:"Civil Lines",type:"Homestay",price:2500,capacity:2,rooms:2,image:"assets/optimized/images-jaipur-jaipur-2.webp",tag:"A personal touch",amenities:["Wi-Fi","Breakfast"],description:"A homely base for exploring the Pink City.",details:"A simple, welcoming room with shared sitting areas and a breakfast table to start the morning."},
    {id:"goa-cottage",name:"Coconut Grove Cottages",city:"Goa",area:"South Goa",type:"Resort",price:4800,capacity:2,rooms:3,image:"assets/optimized/property-types-cottages.webp",tag:"Switch off",amenities:["Wi-Fi","Pool","Parking"],description:"A green hideout for a gentler weekend.",details:"A cottage-style room with a small outdoor seating area and access to a shared pool."},
    {id:"bengaluru-garden",name:"Garden City Residence",city:"Bengaluru",area:"Whitefield",type:"Hotel",price:3900,capacity:3,rooms:5,image:"assets/optimized/images-bengaluru-bengaluru-3.webp",tag:"Work meets weekend",amenities:["Wi-Fi","Breakfast","Parking"],description:"A comfortable pause between city plans.",details:"A spacious room with a desk, double bed and optional extra bed for a third guest."}
  ]
};
