const {test}=require("node:test");
const assert=require("node:assert/strict");
global.window=global;
require("../js/properties.js");
require("../js/catalogue.js");
const {filter,validDate,estimate}=global.HotelVistaCatalogue;
const properties=global.HOTEL_VISTA.properties;
const base={query:"",guests:2,rooms:1,budget:15000,types:[],amenities:[],sort:"recommended",savedOnly:false};
const find=(override={},saved=new Set())=>filter(properties,{...base,...override},saved);
test("default catalogue contains twelve uniquely identified stays",()=>{assert.equal(find().length,12);assert.equal(new Set(properties.map(p=>p.id)).size,12);});
test("Delhi and Bengaluru aliases find the intended cities",()=>{assert.equal(find({query:"Delhi"}).length,2);assert.equal(find({query:"New Delhi"}).length,2);assert.equal(find({query:" Bangalore "}).length,2);});
test("property name and neighbourhood search work",()=>{assert.equal(find({query:"Garden House"})[0].id,"delhi-garden");assert.equal(find({query:"Aerocity"})[0].id,"delhi-studio");});
test("combined city, type, amenity and budget filters intersect",()=>{assert.deepEqual(find({query:"Goa",types:["Resort"],amenities:["Pool","Parking"],budget:5000}).map(p=>p.id),["goa-cottage"]);});
test("unmatched queries and restrictive budgets are empty",()=>{assert.equal(find({query:"Atlantis"}).length,0);assert.equal(find({budget:2000}).length,0);});
test("sorting is numeric and does not mutate the catalogue",()=>{const ids=properties.map(p=>p.id);assert.equal(find({sort:"price-low"})[0].price,2500);assert.equal(find({sort:"price-high"})[0].price,7900);assert.deepEqual(properties.map(p=>p.id),ids);});
test("saved-only returns only saved IDs",()=>{assert.deepEqual(find({savedOnly:true},new Set(["goa-palms"])).map(p=>p.id),["goa-palms"]);assert.equal(find({savedOnly:true}).length,0);});
test("capacity and room quantity are both enforced",()=>{assert.deepEqual(find({guests:4}).map(p=>p.id),["chennai-coast"]);assert.equal(find({rooms:8,guests:16})[0].id,"mumbai-harbour");assert.equal(find({rooms:8,guests:20}).length,0);});
test("calendar dates reject malformed and impossible dates",()=>{assert.equal(validDate("2028-02-29"),true);for(const d of ["2027-02-29","2026-02-30","2026-13-01","2026-2-1","bad",""])assert.equal(validDate(d),false);});
test("estimates multiply rate by nights by rooms",()=>{assert.deepEqual(estimate(4500,"2026-12-30","2027-01-02",2),{nights:3,subtotal:27000});});
test("same-day, reversed and invalid trips cannot be priced",()=>{assert.throws(()=>estimate(4500,"2026-12-30","2026-12-30",1));assert.throws(()=>estimate(4500,"2026-12-30","2026-12-29",1));assert.throws(()=>estimate(4500,"2026-02-30","2026-03-03",1));assert.throws(()=>estimate(4500,"2026-12-30","2027-01-02",0));});
