const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const {randomUUID}=require('node:crypto');
const source=fs.readFileSync('frontend/js/pages/movies.js','utf8');
const tick=()=>new Promise(setImmediate);
function setup({anonymous=false,bookError=false,priceChange=false}={}){
 class Node{constructor(){this.children=[];this.listeners={};this.attrs={};this.value='';}set textContent(v){this.text=v;this.children=[];}get textContent(){return this.text||'';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;}addEventListener(e,fn){this.listeners[e]=fn;}setAttribute(k,v){this.attrs[k]=v;}focus(){}scrollIntoView(){}async click(){return this.listeners.click?.({currentTarget:this});}}
 const nodes={},el=id=>nodes[id]||=new Node();let seatCalls=0,bookCalls=[],redirect;const saved={};
 const screening={id:7,cinema_name:'Demo cinema',city:'Bhopal',starts_at:'2027-12-20T12:30:00Z',timezone:'Asia/Kolkata'};
 const api={movies:async()=>({items:[{id:1,title:'Demo film',language:'Hindi',duration_minutes:120}],page:0,hasNext:false}),shows:async()=>({items:[screening],page:0,hasNext:false}),seats:async()=>{seatCalls++;return [{label:'A1',price:priceChange&&seatCalls>1?300:250,available:true}]},list:async()=>({items:[],page:0,hasNext:false}),book:async r=>{bookCalls.push({...r});if(bookError&&bookCalls.length===1)throw Object.assign(Error('Connection lost'),{status:0});return {reference:'VM-test',status:'CONFIRMED'};}};
 const window={addEventListener(){},confirm:()=>true};window.window=window;
 vm.runInNewContext(source,{window,document:{getElementById:el,createElement:()=>new Node()},VistaMovies:{createClient:()=>api},HotelVistaAuth:{createClient:()=>({me:async()=>anonymous?null:{id:5}})},fetch(){},sessionStorage:{setItem:(k,v)=>saved[k]=v,getItem:k=>saved[k],removeItem:k=>delete saved[k]},location:{assign:v=>redirect=v},crypto:{randomUUID},Intl,Date,URLSearchParams,setTimeout,confirm:()=>true});
 return {el,saved,bookCalls,get redirect(){return redirect},async select(){await tick();await el('movie-list').children[0].children.at(-1).click();await tick();await el('show-list').children[0].children.at(-1).click();await tick();await el('seat-map').children[0].children[1].click();}};
}
test('selected seats survive sign-in redirect without booking',async()=>{const s=setup({anonymous:true});await s.select();await s.el('movie-confirm').click();assert.equal(s.redirect,'/login.html?return=movies');assert.deepEqual(JSON.parse(Object.values(s.saved)[0]).seats,['A1']);assert.equal(s.bookCalls.length,0);});
test('uncertain booking retry reuses request key and exact total',async()=>{const s=setup({bookError:true});await s.select();await s.el('movie-confirm').click();assert.equal(s.el('movie-confirm').textContent,'Retry same reservation');await s.el('movie-confirm').click();assert.equal(s.bookCalls.length,2);assert.equal(s.bookCalls[0].requestKey,s.bookCalls[1].requestKey);assert.equal(s.bookCalls[1].expectedTotal,250);assert.equal(Object.keys(s.saved).length,0);});
test('changed price requires review before sending a reservation',async()=>{const s=setup({priceChange:true});await s.select();await s.el('movie-confirm').click();assert.equal(s.bookCalls.length,0);assert.match(s.el('movie-status').textContent,/prices changed/);await s.el('movie-confirm').click();assert.equal(s.bookCalls[0].expectedTotal,300);});
